<?php
    // +----------------------------------------------------------------------
    // | Z Framework [ The Fast Php Framework ]
    // +----------------------------------------------------------------------
    // | Copyright (c) 2016~2018 http://z_framework.fastrun.cn All rights reserved.
    // +----------------------------------------------------------------------
    // | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
    // +----------------------------------------------------------------------
    // | Author: 张吉凯 <919342864@qq.com>
    // +----------------------------------------------------------------------
    // | Github: CrazyCodes <https://github.com/CrazyCodes>
    // +----------------------------------------------------------------------
    namespace Zero\Tests\Http;
    
    use PHPUnit\Framework\TestCase;
    use Zero\Http\Request;
    
    class RequestTest extends TestCase
    {
        public $request;
        
        public function setUp()
        {
            parent::setUp(); // TODO: Change the autogenerated stub
            $this->request = new Request();
        }
    
        public function testGet()
        {
            $_GET["user_id"] = '2';
            $this->assertEquals(2, $this->request->get("user_id"));
        }
        
        public function testInput()
        {
            $_REQUEST["username"] = 2;
            $this->assertEquals(2, $this->request->input("username"));
        }
    }