<?php
    // +----------------------------------------------------------------------
    // | Z Framework [ The Fast Php Framework ]
    // +----------------------------------------------------------------------
    // | Copyright (c) 2016~2018 http://z_framework.fastrun.cn All rights reserved.
    // +----------------------------------------------------------------------
    // | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
    // +----------------------------------------------------------------------
    // | Author: 张吉凯 <919342864@qq.com>
    // +----------------------------------------------------------------------
    // | Github: CrazyCodes <https://github.com/CrazyCodes>
    // +----------------------------------------------------------------------
    namespace Zero\Tests;
    
    use PHPUnit\Framework\TestCase;
    use Zero\Routing\RouteCollection;
    use Zero\Routing\RouteModel;
    
    /**
     * Class RouteCollectionTest
     * @package Zero\Tests
     */
    class RouteCollectionTest extends TestCase
    {
        protected $routeCollection;
        
        public function setUp()
        {
            parent::setUp();
            
            $this->routeCollection = new RouteCollection();
        }
        
        /**
         * @content Cut routing parameters
         */
        public function testBreakUpString()
        {
            $sim = "TestController@Get";
            
            $response = $this->routeCollection->breakUpString($sim);
            
            $this->assertIsArray($response);
            
            $this->assertStringContainsString("TestController", $response[0]);
            $this->assertStringContainsString("Get", $response[1]);
        }
        
        /**
         * @content add route to $_SERVER
         */
        public function testAdd()
        {
            $requestUrl = "domain/test";
            
            $routeTemplate         = new RouteModel();
            $routeTemplate->method = "GET";
            $routeTemplate->action = "TestController@test";
            
            $this->routeCollection->add($requestUrl, $routeTemplate);
            
            $this->assertArrayHasKey($requestUrl, $_SERVER['routes']);
        }
        
        public function tearDown()
        {
            parent::tearDown(); // TODO: Change the autogenerated stub
            
            unset($this->routeCollection);
        }
    }